version: '3.8'

volumes: 
  mongo_vol:

networks:
  produto_net:
    driver: bridge

services:
  api:
    image: gmaceu/api-produto:${tag}
    build:
      dockerfile: ./Dockerfile
      context: ../api-produto/src
    ports: 
      - 8080:8080
    networks:
      - produto_net
    environment:
      MONGODB_URI: mongodb://mongouser:mongopwd@localhost:27017/admin
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:4.4.3
    ports: 
      - 27017:27017
    networks:
      - produto_net
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd