apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: web
    versao: blue
spec:
  containers:
    - name: webapp
      image: kubedevio/web-color:blue
      ports: 
        - name: http
          containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: web
    versao: green
spec:
  containers:
    - name: webapp
      image: kubedevio/web-color:green
      ports: 
        - name: http
          containerPort: 80
          protocol: TCP