apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset1
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: webapp
          image: kubedevio/web-color:green
          ports: 
            - name: http
              containerPort: 80
              protocol: TCP